# Generated by Django 5.2.17 on 2026-10-03 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(max_length=160)),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("item", "Item"),
                            ("unitemised", "Unitemised purchase"),
                            ("shipping", "Shipping"),
                            ("discount", "Discount"),
                            ("rounding", "Rounding"),
                            ("adjustment", "Other adjustment"),
                            ("refund", "Refund"),
                        ],
                        default="item",
                        max_length=12,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("material", "Material"),
                            ("tool", "Tool"),
                            ("labour", "Labour"),
                            ("other", "Other"),
                        ],
                        default="material",
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Descriptive only; totals use the line amount.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Signed line total (discounts negative).",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="CostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("shared_tools", "Shared tools"),
                            ("unallocated", "Unallocated"),
                        ],
                        max_length=14,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpeningCostBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining estimate after replacements.",
                        max_digits=10,
                    ),
                ),
                (
                    "coverage_through",
                    models.DateField(
                        help_text="Spending up to and including this date is covered by the estimate."
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("is_estimate", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["coverage_through", "id"],
            },
        ),
        migrations.CreateModel(
            name="OpeningBalanceDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("additional", "Additional spending"),
                            ("replace", "Replaces part of the estimate"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount_replaced",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="costs.openingcostbalance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("purchase", "Purchase"), ("refund", "Refund")],
                        default="purchase",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("confirmed", "Confirmed"), ("void", "Void")],
                        default="confirmed",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=160)),
                ("merchant", models.CharField(blank=True, max_length=120)),
                ("transaction_date", models.DateField()),
                ("currency", models.CharField(default="GBP", max_length=3)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("void_reason", models.TextField(blank=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("submission_key", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "original_purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="costs.purchase",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
