# Generated by Django 5.2.17 on 2026-10-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("costs", "0001_initial"),
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="source_draft",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posted_purchase",
                to="receipts.receiptdraft",
            ),
        ),
        migrations.AddField(
            model_name="openingbalancedecision",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_decisions",
                to="costs.purchase",
            ),
        ),
        migrations.AddField(
            model_name="purchaseevidence",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_links",
                to="receipts.receiptdocument",
            ),
        ),
        migrations.AddField(
            model_name="purchaseevidence",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="costs.purchase",
            ),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="costs.purchase",
            ),
        ),
        migrations.AddField(
            model_name="costallocation",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="costs.purchaseline",
            ),
        ),
        migrations.AddConstraint(
            model_name="openingcostbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="opening_balance_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="openingcostbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_amount__gte", 0)),
                name="opening_balance_original_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="openingcostbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__lte", models.F("original_amount"))),
                name="opening_balance_not_above_original",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0)),
                name="purchase_total_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency", "GBP")), name="purchase_currency_gbp"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "purchase"), ("original_purchase__isnull", True)),
                    models.Q(("kind", "refund"), ("total__gt", 0)),
                    _connector="OR",
                ),
                name="purchase_refund_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "confirmed"),
                    models.Q(("void_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="purchase_void_needs_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                fields=("owner", "submission_key"), name="purchase_unique_submission"
            ),
        ),
        migrations.AddConstraint(
            model_name="openingbalancedecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_replaced__gte", 0)),
                name="decision_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="openingbalancedecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("amount_replaced__gt", 0), ("decision", "replace")),
                    models.Q(("amount_replaced", 0), ("decision", "additional")),
                    _connector="OR",
                ),
                name="decision_amount_matches_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseevidence",
            constraint=models.UniqueConstraint(
                fields=("purchase", "document"), name="unique_purchase_evidence"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="line_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("line_type", "discount"), _negated=True),
                    ("amount__lt", 0),
                    _connector="OR",
                ),
                name="line_discount_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("line_type__in", ["item", "unitemised", "shipping", "refund"]),
                        _negated=True,
                    ),
                    ("amount__gte", 0),
                    _connector="OR",
                ),
                name="line_item_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("destination", "project"), ("project__isnull", False)),
                    models.Q(
                        models.Q(("destination", "project"), _negated=True),
                        ("project__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="allocation_project_matches_destination",
            ),
        ),
    ]
