# Generated by Django 5.2.17 on 2026-10-03 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("costs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("storage_key", models.CharField(max_length=255)),
                ("original_filename", models.CharField(blank=True, max_length=120)),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("mime", models.CharField(max_length=40)),
                ("size", models.PositiveIntegerField()),
                ("page_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "preview_key",
                    models.CharField(
                        blank=True,
                        help_text="Browser-viewable JPEG for HEIC originals.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Editable draft values; never read by cost totals.",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed as purchase"),
                            ("attached", "Attached to existing purchase"),
                            ("discarded", "Discarded"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("duplicate_acknowledged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "attached_purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attached_drafts",
                        to="costs.purchase",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft",
                        to="receipts.receiptdocument",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("succeeded", "Ready for review"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("adapter", models.CharField(blank=True, max_length=40)),
                ("model_version", models.CharField(blank=True, max_length=80)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=2)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("draft_json", models.JSONField(blank=True, null=True)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("usage", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="receipts.receiptdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["queued", "processing"])),
                        fields=("document",),
                        name="one_active_job_per_document",
                    )
                ],
            },
        ),
    ]
