# Generated by Django 5.2.17 on 2026-10-03 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionjob",
            name="available_at",
            field=models.DateTimeField(
                blank=True, help_text="Earliest time a retry may be claimed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="extractionjob",
            name="claim_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractionjob",
            name="draft",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="receipts.receiptdraft",
            ),
        ),
        migrations.AddField(
            model_name="extractionjob",
            name="error_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="extractionjob",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractionjob",
            name="requested_draft_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="extractionjob",
            name="result_state",
            field=models.CharField(
                choices=[
                    ("none", "No result"),
                    ("applied", "Applied to the draft"),
                    ("held", "Held: draft changed while reading"),
                    ("discarded", "Not applied: receipt already handled"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="extractionjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="extractionjob",
            name="draft_json",
            field=models.JSONField(
                blank=True,
                help_text="Normalised draft values (never read by cost totals).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractionjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Waiting to be read"),
                    ("processing", "Reading"),
                    ("succeeded", "Read"),
                    ("failed", "Could not be read"),
                ],
                default="queued",
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts__lte", models.F("max_attempts"))),
                name="job_attempts_bounded",
            ),
        ),
    ]
