# Generated by Django 5.2.17 on 2026-10-05 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("receipts", "0002_extraction_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptdraft",
            name="context_project",
            field=models.ForeignKey(
                blank=True,
                help_text="The owner's project this receipt was started from. Only pre-selects the 'Assign unassigned items to' choice; it never allocates or records anything by itself.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="projects.project",
            ),
        ),
    ]
